[package]
name = "ShelbyworldQuest"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
game_addr = "_"   # Will be automatically bound to the new Resource Account address
admin_addr = "_"  # Will be mapped to your deploying standard wallet address

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }